version: "3"
services:
  test_server:
    image: liubang/java8
    hostname: test_server
    environment:
      SERVICE_8080_NAME: test_server
      SERVICE_TAGS: service
      MY_HOST: test_server
    networks:
      - backend
    volumes:
      - ./test-service-0.0.1-SNAPSHOT.jar:/data/project/app.jar
    ports:
      - 8080:8080
    command: java -jar -Dserver.port=8080 /data/project/app.jar
  consul:
    image: liubang/consul:1.2.3
    hostname: consulserver
    networks:
      - backend
    ports:
      - 8300
      - 53
      - 8500:8500
      - 8600:8600
    command: agent -server -ui --data-dir /tmp/consul -bootstrap-expect 1 -bind 0.0.0.0 -client 0.0.0.0
  loadbalancer:
    image: liubang/openresty-consul-template
    hostname: loadbalancer
    volumes:
      - ./nginx.conf.ctmpl:/opt/app/nginx/conf/vhost/nginx.conf.ctmpl
    networks:
      - backend
    links:
      - consul:consul
    ports:
      - 80:80
  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator
    networks:
      - backend
    links:
      - consul:consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
networks:
  backend:


