version: "3"
services:
  test_server:
    image: liubang/java8
    hostname: test_server
    environment:
      SERVICE_8080_NAME: test_server
      SERVICE_TAGS: service-821
      MY_HOST: test_server-821
    networks:
      - backend
    volumes:
      - ../test-service-0.0.1-SNAPSHOT.jar:/data/project/app.jar
    ports:
      - 8080
    command: java -jar -Dserver.port=8080 /data/project/app.jar
  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator-821
    networks:
      - backend
    depends_on:
      - test_server
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip 192.168.8.21 consul://192.168.8.20:8500
networks:
  backend:
