dist: bionic
sudo: required

matrix:
  include:
    - language: go
      go:
        - 1.16.x
      before_install:
        - export GO111MODULE=on
        - export GOPATH=${HOME}/.go
      install:
        - go env
      script:
        - cd go
        - go test ./...
      cache:
        directories:
          - $HOME/.go
    - language: java
      jdk:
        - oraclejdk9
      script:
        - cd java
        - mvn test
      cache:
        directories:
          - $HOME/.m2
    - language: cpp
      env:
        - OLC_PATH=cpp
        - V=3.7.0
        - CXX=g++-10
        - CC=gcc-10
      compiler:
        - gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-10
            - g++10
      before_install:
        - OS=linux
        - ARCH=x86_64
        - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
        - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
        - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
        - CI_ARTIFACT="bazel--installer.sh"
        - URL="$GH_BASE/$GH_ARTIFACT"
        - if [[ "$V" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
        - if [[ "$V" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
        - echo $URL
        - wget -O install.sh $URL
        - chmod +x install.sh
        - ./install.sh --user
        - rm -f install.sh
        - echo ${CC}
        - echo ${CXX}
        - ${CXX} --version
      script:
        - cd cpp
        - bazel test //...
      cache:
        directories:
          - $HOME/.cache/bazel
