---
name: build-java
on:
  push:
    branches:
      - main
    paths:
      - "MODULE.bazel"
      - "java/**"
      - ".github/workflows/build_java.yml"
  workflow_dispatch:

jobs:
  build-java:
    name: java playground
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        env:
          cache-name: bazel-java
        with:
          path: ~/.cache/bazel
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}

      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: false
          repository-cache: true

      - name: build and test
        run: |
          bazelisk build //java/...
