---
name: build-cpp
on:
  push:
    branches:
      - main
    paths:
      - "cpp/**"
      - ".github/workflows/build_cpp.yml"
  workflow_dispatch:

jobs:
  build-cpp:
    name: cpp playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.0"
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - uses: actions/cache@v3
        env:
          cache-name: bazel
        with:
          path: ~/.cache/bazelisk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}
      - run: go install github.com/bazelbuild/bazelisk@latest
      - name: run build
        run: |
          cd cpp
          bazelisk build //basecode/...
          bazelisk query "kind('cc_binary', //highkyck/misk/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/utils/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/meta/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/trace/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/brain_fuck/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/cpp14/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/cpp17/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/cpp20/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/misk/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/meta/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk build //highkyck/bfcc/...
          bazelisk test  //algo/...
          bazelisk test  //highkyck/arena/...
          bazelisk test  //highkyck/bfcc/...
          bazelisk test  //highkyck/cppstories/...
          bazelisk test  //test/misk/...


