---
name: build-java
on:
  push:
    branches:
      - main
    paths:
      - "java/**"
      - ".github/workflows/build_java.yml"
  workflow_dispatch:

jobs:
  build-java:
    name: java playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.0"
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64
      - uses: actions/cache@v3
        env:
          cache-name: bazel
        with:
          path: ~/.cache/bazelisk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}

      - name: build and test
        run: |
          bazelisk build //java/...
          bazelisk test  //java/...
