---
name: build-cpp
on:
  push:
    branches:
      - main
    paths:
      - "cpp/**"
      - ".github/workflows/build_cpp.yml"
  workflow_dispatch:

jobs:
  build-cpp:
    name: cpp playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - uses: actions/cache@v4
        env:
          cache-name: bazel-cpp
        with:
          path: bazel-disk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: ${{ env.cache-name }}-${{ runner.os }}
          save-always: true
      - run: go install github.com/bazelbuild/bazelisk@latest
      - run: sudo apt update
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: build and test
        run: |
          bazelisk build --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
          bazelisk test --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
  coverage:
    name: code coverage
    runs-on: ubuntu-latest
    needs: [build-cpp]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - uses: actions/cache@v4
        env:
          cache-name: bazel-coverage
        with:
          path: bazel-disk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: ${{ env.cache-name }}-${{ runner.os }}
      - run: go install github.com/bazelbuild/bazelisk@latest
      - run: sudo apt update
      - run: sudo apt install lcov
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: run build
        run: |
          bazelisk coverage --disk_cache=bazel-disk --action_env=CC=gcc-12 --instrument_test_targets --combined_report=lcov //cpp/...
          genhtml --output coverage "./bazel-out/_coverage/_coverage_report.dat"
          cp -r ./registry ./coverage/
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: coverage
          user_name: "liubang"
          user_email: "it.liubang@gmail.com"
