---
name: build-java
on:
  push:
    branches:
      - main
    paths:
      - "java/**"
      - ".github/workflows/build_java.yml"
  workflow_dispatch:

jobs:
  build-java:
    name: java playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: build with maven
        run: cd java && mvn package
