---
name: build-python
on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/build_python.yml"
  workflow_dispatch:

jobs:
  build-go:
    name: go playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.0"
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        env:
          cache-name: bazel-python
        with:
          path: "~/.cache/bazel"
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}

      - name: build and test
        run: |
          bazelisk build //python/...
          bazelisk test  //python/...
