---
name: build-cpp
on:
  push:
    branches:
      - main
    paths:
      - "cpp/**"
      - ".github/workflows/build_cpp.yml"
  workflow_dispatch:

jobs:
  build-cpp:
    name: cpp playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - uses: actions/cache@v4
        env:
          cache-name: bazel-cpp
        with:
          path: bazel-disk
          key: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-${{github.sha}}
          restore-keys: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-
          save-always: true
      - run: sudo apt update
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: build and test
        run: |
          bazel build -c opt --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
          bazel test -c opt --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
  coverage:
    name: code coverage
    runs-on: ubuntu-latest
    needs: [build-cpp]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - uses: actions/cache@v4
        env:
          cache-name: bazel-coverage
        with:
          path: bazel-disk
          key: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-${{github.sha}}
          restore-keys: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-
          save-always: true
      - run: sudo apt install lcov
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: run build
        run: |
          bazel coverage --action_env=CC=gcc-12 --disk_cache=bazel-disk --verbose_failures --combined_report=lcov --instrumentation_filter='cpp,-cpp/copts' cpp/...
          ls -lh ./bazel-out/_coverage/_coverage_report.dat
          genhtml --output coverage ./bazel-out/_coverage/_coverage_report.dat
          cp -r ./registry ./coverage/
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: coverage
          user_name: "liubang"
          user_email: "it.liubang@gmail.com"
