---
name: build-cpp
on:
  push:
    branches:
      - main
    paths:
      - "cpp/**"
      - ".github/workflows/build_cpp.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        env:
          cache-name: build
        with:
          path: bazel-disk
          key: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-${{github.sha}}
          restore-keys: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-
          save-always: true
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: false
          repository-cache: false
      - run: sudo apt update
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: run build
        run: |
          bazel build -c opt --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
  test:
    name: test
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        env:
          cache-name: test
        with:
          path: bazel-disk
          key: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-${{github.sha}}
          restore-keys: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-
          save-always: true
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: false
          repository-cache: false
      - run: sudo apt update
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: run test
        run: |
          bazel test -c opt --action_env=CC=gcc-12 --disk_cache=bazel-disk //cpp/...
  coverage:
    name: coverage
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        env:
          cache-name: coverage
        with:
          path: bazel-disk
          key: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-${{github.sha}}
          restore-keys: ${{ github.workflow }}-${{ env.cache-name }}-${{ runner.os }}-
          save-always: true
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: false
          repository-cache: true
      - run: sudo apt install lcov
      - run: sudo apt install yasm
      - run: sudo apt install nasm
      - name: run coverage
        run: |
          bazel coverage --action_env=CC=gcc-12 --disk_cache=bazel-disk --verbose_failures --combined_report=lcov --instrument_test_targets cpp/...
          ls -lh ./bazel-out/_coverage/_coverage_report.dat
          genhtml --ignore-errors --output coverage ./bazel-out/_coverage/_coverage_report.dat
          cp -r ./registry ./coverage/
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: coverage
          user_name: "liubang"
          user_email: "it.liubang@gmail.com"
