---
name: master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - uses: actions/cache@v2
        env:
          cache-name: bazel
        with:
          path: ~/.cache/bazelisk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}
      - run: go get github.com/bazelbuild/bazelisk
      - name: run build
        run: |
          cd cpp
          bazelisk build //basecode/...
          bazelisk query "kind('cc_binary', //highkyck/misk/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/meta/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/trace/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //highkyck/brain_fuck/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/cpp17/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk query "kind('cc_binary', //test/cpp20/...)" --keep_going --noshow_progress --output=label  | xargs bazelisk run
          bazelisk build //highkyck/bfcc/...
          bazelisk test  //algo/...
          bazelisk test  //highkyck/arena/...
          bazelisk test  //highkyck/bfcc/...
          bazelisk test  //highkyck/cppstories/...
          bazelisk test  //test/misk/...
